export enum FeatureFlags {
  insightsRecommendations = 'insightsRecommendations',
  cloudSso = 'cloudSso',
  cloudSsoRecommendedSettings = 'cloudSsoRecommendedSettings',
  databaseChat = 'databaseChat',
  documentationChat = 'documentationChat',
  envDependent = 'envDependent',
  rdi = 'redisDataIntegration',
  hashFieldExpiration = 'hashFieldExpiration',
  enhancedCloudUI = 'enhancedCloudUI',
  cloudAds = 'cloudAds',
  databaseManagement = 'databaseManagement',
  vectorSearchV2 = 'vectorSearchV2',
  devVectorSet = 'dev-vectorSet',
  azureEntraId = 'azureEntraId',
  devBrowser = 'dev-browser',
}
